name: Deploy Vue to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn browser:build

      - name: Fix CDN paths in index.html
        run: |
          cd dist
          sudo apt-get install dos2unix -y
          dos2unix index.html
          sed -i -E 's/(href|src)="\/(static\/[^"]+)"/\1="https:\/\/cdn.jsdelivr.net\/gh\/shiyuq\/love-shiqinyue@gh-pages\/\2"/g' index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
